"""journal add diff quartiles

Revision ID: 05bc6d703cb1
Revises: 5409fa46330e
Create Date: 2020-03-19 09:10:59.160607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bc6d703cb1'
down_revision = '5409fa46330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal") as batch_op:
        batch_op.add_column(sa.Column('quartile_JCR', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quartile_SJR', sa.Integer(), nullable=True))
        batch_op.drop_column('quartile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal") as batch_op:
        batch_op.add_column(sa.Column('quartile', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quartile_SJR')
        batch_op.drop_column('quartile_JCR')
    # ### end Alembic commands ###
