"""delete uneeded table asynonyms

Revision ID: 5409fa46330e
Revises: fda7df4c1bf2
Create Date: 2020-03-18 20:23:47.099434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5409fa46330e'
down_revision = 'fda7df4c1bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_synonym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_synonym',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('main_id', sa.INTEGER(), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('patronymic', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['main_id'], ['author.id'], name='main_id_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
