"""init

Revision ID: 7d6059dd0234
Revises: 
Create Date: 2020-03-18 12:03:14.171401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6059dd0234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('ename', sa.String(length=255), nullable=True),
    sa.Column('epatronymic', sa.String(length=255), nullable=True),
    sa.Column('elastname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8128), nullable=True),
    sa.Column('quartile', sa.Integer(), nullable=True),
    sa.Column('is_wos', sa.Boolean(), nullable=True),
    sa.Column('is_scopus', sa.Boolean(), nullable=True),
    sa.Column('is_risc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_organisation',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='author_id_fk'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name='organisation_id_fk')
    )
    op.create_table('author_synonym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_id', sa.Integer(), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['main_id'], ['author.id'], name='main_id_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8128), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('issue', sa.String(length=250), nullable=True),
    sa.Column('pages', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=250), nullable=True),
    sa.Column('authors_raw', sa.String(length=250), nullable=True),
    sa.Column('pub_type', sa.Enum('ConfThesis', 'Proceedings', 'Article', 'Monograph', 'Patent', 'PhdThesis', 'DocThesis', 'Awards', name='pubtype'), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name='journal_id_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_publication',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='author_id_fk'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], name='publication_id_fk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_publication')
    op.drop_table('publication')
    op.drop_table('author_synonym')
    op.drop_table('author_organisation')
    op.drop_table('organisation')
    op.drop_table('journal')
    op.drop_table('author')
    # ### end Alembic commands ###
