"""extend pub_auth table

Revision ID: 8735cbf3d445
Revises: 23ebb313a76a
Create Date: 2020-04-15 19:03:00.037701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8735cbf3d445'
down_revision = '19d2ace01d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_publication', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_publication', 'order')
    # ### end Alembic commands ###
