"""cascading in author_publication

Revision ID: 91bb968b5d35
Revises: 8735cbf3d445
Create Date: 2020-06-17 13:29:57.015155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bb968b5d35'
down_revision = '8735cbf3d445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("author_publication") as batch_op:
        batch_op.drop_constraint('author_id_fk',  type_='foreignkey')
        batch_op.drop_constraint('publication_id_fk',  type_='foreignkey')
        batch_op.create_foreign_key('author_id_fk',  'author', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('publication_id_fk',  'publication', ['publication_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("author_publication") as batch_op:
        batch_op.drop_constraint('publication_id_fk',  type_='foreignkey')
        batch_op.drop_constraint('author_id_fk',  type_='foreignkey')
        batch_op.create_foreign_key('publication_id_fk', 'publication', ['publication_id'], ['id'])
        batch_op.create_foreign_key('author_id_fk',  'author', ['author_id'], ['id'])
    # ### end Alembic commands ###
