"""new author_publication column

Revision ID: 9453031afe3a
Revises: 91bb968b5d35
Create Date: 2020-06-22 17:37:36.563286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9453031afe3a'
down_revision = '91bb968b5d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_publication', sa.Column('main_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_publication', 'main_id')
    # ### end Alembic commands ###
