"""mistake in column name

Revision ID: c1dca6c0013e
Revises: 65dbd258f55f
Create Date: 2020-03-16 21:23:31.243855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dca6c0013e'
down_revision = '65dbd258f55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal") as batch_op:
        batch_op.add_column(sa.Column('quartile', sa.Integer))
        batch_op.drop_column('quartille')  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal") as batch_op:
        batch_op.add_column(sa.Column('quartille', sa.Integer))
        batch_op.drop_column('quartile')  
    # ### end Alembic commands ###
