"""initial

Revision ID: fd099bae891c
Revises: 
Create Date: 2020-03-03 17:43:46.795438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd099bae891c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8128), nullable=True),
    sa.Column('quartille', sa.Integer(), nullable=True),
    sa.Column('is_wos', sa.Boolean(), nullable=True),
    sa.Column('is_scopus', sa.Boolean(), nullable=True),
    sa.Column('is_risc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8128), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('issue', sa.String(length=250), nullable=True),
    sa.Column('pages', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=250), nullable=True),
    sa.Column('authors_raw', sa.String(length=250), nullable=True),
    sa.Column('pub_type', sa.Enum('ConfThesis', 'Proceedings', 'Article', 'Monograph', 'Patent', 'PhdThesis', 'DocThesis', 'Awards', name='pubtype'), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication')
    op.drop_table('journal')
    # ### end Alembic commands ###
